sudo: required
services:
  - docker

before_install:
  - docker build -t xrchitron/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true xrchitron/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-1"
  app: "Docker-test"
  env: "Docker-test-env"
  bucket_name: "elasticbeanstalk-ap-northeast-1-343534424551"
  bucket_path: "Docker-test"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"